import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import FooterLinks from "@/components/footer-links";
import LogoDep from "@/components/logo";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="tr">
      <body className="max-w-[90%] mx-auto overflow-x-hidden relative w-screen h-screen">
        <main className="min-[2000px]:scale-120 min-[2500px]:scale-150 min-[2000px]:origin-top ">
          {children}
        </main>
        <LogoDep />
      </body>
    </html>
  );
}
